config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments, :except => [:index,:show]
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :content
  validates :content,:presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title,:content,:presence => true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :find_post
	before_filter :find_comment, :only => [:edit , :update , :destroy]

	def new
		@comment = @post.comments.build
	end

	def create
		@comment = @post.comments.build(params[:comment])

		if @comment.save
			redirect_to @post,:notice => "Comment added successfully"
		else
			render :action => "new"
		end
	end

	def edit

	end

	def update
		if @comment.update_attributes(params[:comment])
			redirect_to @post, :notice => "Comment edited successfully"
		else
			render :action => "new"
		end
	end

	def destroy
		@comment.destroy
		redirect_to @post, :notice => "Comment deleted"
	end
	
	private
	def find_post
		@post = Post.find(params[:post_id])
	end

	private
	def find_comment
		@comment = Comment.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :find_post, :only => [:edit,:update,:show,:destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post])

		if @post.save
			redirect_to @post, :notice => "Post has been successfully created"
		else
			flash[:alert] = "Post creation failed"
			render :action => "new"
		end
	end

	def edit

	end

	def update
		if @post.update_attributes(params[:post])
			redirect_to @post, :notice => "Post edited successfully"
		else
			flash[:alert] = "Could not edit post"
			render :action => "edit"
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path , :notice => "Post has been deleted"
	end

	private
	def find_post
		@post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post,@comment], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Add Comment", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h2> Edit comment </h2>
<%= render 'form' %>

app/views/comments/new.html.erb
<h2> New Comment </h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-responsive-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Blog</a>
          <div class="container nav-collapse">
            
            <ul class="nav pull-right">
              <li><%= link_to "New Post", new_post_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
         <%= bootstrap_flash %>
         
          <%= yield %>
         
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<div>
  <% @posts.each do |post| %>
   <div class="container">
      <div class = "row span5 ">
        <h4> <%= link_to post.title, post %> </h4>
      </div>

      <div class = "row span8 offset1">
        <%= post.content %>
      </div>
      <br/><br/>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<div class = "container">
	<div class="container post">
		<div class = "row span5 ">
			<h2> <%= @post.title %> </h2>
		</div>

		<div class = "row span10 offset1">
			<%= @post.content %>
		</div>

		<div class="pull-left">
			<%= link_to "Write a comment", new_post_comment_path(@post) %>
		</div>

		<div class="pull-right">
			<%= link_to "Edit Post", edit_post_path(@post) %>
			<%= link_to "Delete Post", @post , :method => 'delete', :confirm => 'Are you sure?', 
				:class => 'btn btn-danger btn-small' %>
		</div>
	</div>

	<div class = "container comments">
		<table class="table table-striped span8 offset2">
			<tbody>
				<% @post.comments.each do |comment| %>
					
						<tr>
							<td class="span6"><%= comment.content %></td>
							<td class="pull-right span1"> 
								<%= link_to "Delete Comment", [@post,comment], :method => :delete, :confirm =>"Are you sure?" %>
							</td>
							<td class="pull-right span1"> 
								<%= link_to "Edit Comment", [:edit,@post,comment] %>
							</td>
						</tr>
					
				<%end%>
			</tbody>
		</table>
	</div>
</div>